apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: github
  namespace: group-sync-operator
spec:
  # synchronize every 4 hours
  schedule: "*/10 * * * *"
  providers:
    - name: github
      github:
        organization: "{{ GITHUB_ORG }}"
        prune: true
        credentialsSecret:
          name: github-group-sync
          namespace: group-sync-operator
