apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
labels:
  - pairs:
      app: minio
    includeSelectors: true

resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- console-route.yaml
- object-storage-route.yaml
