---
- name: "Deploy workbenches"
  include_tasks: deploy-workbench.yaml
  loop: "{{ WORKBENCH_NAMES }}"
  vars:
    WORKBENCH_NAMESPACE: "ai-telemetry-cbca60"
    WORKBENCH_NAME: "{{ WORKBENCH_VARS.USER_NAME }}"
    USER_NAME: "{{ WORKBENCH_VARS.USER_NAME }}"
    WORKBENCH_ADMIN: "{{ WORKBENCH_VARS.WORKBENCH_ADMIN is defined and WORKBENCH_VARS.WORKBENCH_ADMIN }}"
    DATABASE_USERNAME: "{{ SITE_SHORT_NAME }}{{ WORKBENCH_VARS.USER_NAME | replace('-', '') | replace('_', '') }}"
    DATABASE_DATABASE: "{{ SITE_SHORT_NAME }}{{ WORKBENCH_VARS.USER_NAME | replace('-', '') | replace('_', '') }}"
    SOLR_COLLECTION: '{{ SITE_SHORT_NAME }}-{{ WORKBENCH_VARS.USER_NAME }}'
    SOLR_COLLECTION_COMPUTATE: 'computate-{{ WORKBENCH_VARS.USER_NAME }}'
  loop_control:
    loop_var: WORKBENCH_VARS
    index_var: WORKBENCH_INDEX
