DROP TABLE AiNode CASCADE;
DROP TABLE AiProject CASCADE;
DROP TABLE AiCluster CASCADE;
DROP TABLE GpuSlice CASCADE;
DROP TABLE GpuDevice CASCADE;
DROP TABLE SiteUser CASCADE;
DROP TABLE ClusterRequest CASCADE;
DROP TABLE ClusterTemplate CASCADE;
