---
- name: "Deploy the PostgresCluster with user workbenches"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'postgrescluster.yaml') }}"
    validate_certs: false
- name: Wait for postgres Ready condition
  kubernetes.core.k8s_info:
    namespace: "{{ SITE_NAMESPACE }}"
    kind: Pod
    label_selectors:
      - postgres-operator.crunchydata.com/role=master
    wait: true
    wait_timeout: 300
    wait_condition:
      type: Ready
      status: 'True'
