kind: ConfigMap
apiVersion: v1
metadata:
  name: workbench-{{ WORKBENCH_NAME }}-{{ SITE_NAME }}
  namespace: {{ WORKBENCH_NAMESPACE }}
data:
  SITE_SRC: "{{ SITE_SRC }}"
  SOLR_COLLECTION_{{ SITE_SHORT_NAME }}: '{{ SOLR_COLLECTION }}'
  DATABASE_USERNAME_{{ SITE_SHORT_NAME }}: "{{ DATABASE_USERNAME }}"
  DATABASE_DATABASE_{{ SITE_SHORT_NAME }}: "{{ DATABASE_DATABASE }}"
  AUTH_NAMESPACE_{{ SITE_SHORT_NAME }}: {{ WORKBENCH_NAMESPACE }}
  AUTH_HOST_NAME_{{ SITE_SHORT_NAME }}: "keycloak.apps.obs.nerc.mghpcc.org"
  AUTH_REALM_{{ SITE_SHORT_NAME }}: "NERC"
  AUTH_CLIENT_{{ SITE_SHORT_NAME }}: "ai-telemetry"
  AUTH_OPENSHIFT_SECRET_{{ SITE_SHORT_NAME }}: "{{ 'keycloak-client-' + AUTH_CLIENT }}"
  AUTH_ADMIN_OPENSHIFT_SECRET_{{ SITE_SHORT_NAME }}: "keycloak-initial-admin-{{ SITE_NAME }}"
  AUTH_ADMIN_USERNAME_{{ SITE_SHORT_NAME }}: "{{ 'admin' }}"
  PROM_KEYCLOAK_PROXY_HOST_NAME: metrics.apps.obs.nerc.mghpcc.org
