kind: ConfigMap
apiVersion: v1
metadata:
  name: workbench-{{ WORKBENCH_NAME }}-default
  namespace: {{ WORKBENCH_NAMESPACE }}
data:
  USING_OPENSHIFT_AI: 'true'
  OPENSHIFT_APPS_DOMAIN: '{{ OPENSHIFT_APPS_DOMAIN }}'
  OPENSHIFT_AI_WORKBENCH: {{ WORKBENCH_NAME }}
  WORKBENCH_ADMIN: '{{ WORKBENCH_ADMIN | string | lower }}'
  SITE_NAMESPACE: {{ WORKBENCH_NAMESPACE }}
  SITE_HOST_NAME: '{{ SITE_SHORT_NAME }}-{{ USER_NAME }}.{{ OPENSHIFT_APPS_DOMAIN }}'
  SITE_BASE_URL: 'https://{{ SITE_SHORT_NAME }}-{{ USER_NAME }}.{{ OPENSHIFT_APPS_DOMAIN }}'
  WEB_COMPONENTS_SECRET: "font-awesome-{{ USER_NAME }}"
  ZOOKEEPER_ROOT_PATH: '{{ SITE_SHORT_NAME }}-{{ USER_NAME }}'
  SSL_VERIFY: 'true'
  ZOOKEEPER_NAMESPACE: {{ WORKBENCH_NAMESPACE }}
  ZOOKEEPER_HOST_NAME: zookeeper
  ZOOKEEPER_PORT: '2181'
  SOLR_NAMESPACE: {{ WORKBENCH_NAMESPACE }}
  SOLR_HOST_NAME: solr
  SOLR_PORT: '8983'
  SOLR_SSL: 'false'
  SOLR_COLLECTION_COMPUTATE: 'computate-{{ USER_NAME }}'
  SOLR_COLLECTION_FIWARE: 'fiware'
  COMPUTATE_SEARCH_SRC: '/opt/app-root/src/computate-search'
  COMPUTATE_VERTX_SRC: '/opt/app-root/src/computate-vertx'
  COMPUTATE_SRC: '/opt/app-root/src/computate'
  CONTEXT_BROKER_NAMESPACE: {{ WORKBENCH_NAMESPACE }}
  CONTEXT_BROKER_SSL: "false"
  CONTEXT_BROKER_HOST_NAME: "scorpiobroker"
  CONTEXT_BROKER_PORT: "9090"
  NGSILD_TENANT: "{{ SITE_SHORT_NAME }}-{{ USER_NAME }}"
  NGSILD_PATH: "/USA"
  NGSILD_TENANT_ENV: "NGSILD_TENANT"
  NGSILD_PATH_ENV: "NGSILD_PATH"
  ENABLE_FIWARE: "{{ ENABLE_FIWARE | string | lower | default('false', true) }}"
  DATABASE_HOST_NAME: "postgres-primary"
  DATABASE_PORT: "5432"
