apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-{{ SITE_SHORT_NAME }}
  namespace: {{ WORKBENCH_NAMESPACE }}
type: Opaque
stringData:
  client: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-client'), namespace='keycloak')[0].data['client'] | b64decode }}"
  secret: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-client'), namespace='keycloak')[0].data['secret'] | b64decode }}"
