apiVersion: v1
kind: Secret
metadata:
  name: postgres-pguser-{{ SITE_SHORT_NAME }}
  namespace: {{ WORKBENCH_NAMESPACE }}
type: Opaque
stringData:
  password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
