apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex
labels:
  - pairs:
      app.kubernetes.io/name: dex
      app.kubernetes.io/component: dex-server
      app.kubernetes.io/part-of: auth
    includeSelectors: true
resources:
- deployments
- routes
- secrets
- serviceaccounts
- services
