apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      nerc.mghpcc.org/kustomized: "true"
    includeSelectors: true

resources:
- ../../../dex/overlays/openshift-local
- ../../../group-sync-operator/overlays/openshift-local
