apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../../../dex/overlays/openshift-local
- ../../../group-sync-operator/overlays/openshift-local
