apiVersion: v1
kind: Secret
metadata:
  namespace: {{ WORKBENCH_NAMESPACE }}
  name: "{{ 'keycloak-client-' + (AUTH_CLIENT | lower ) }}"
type: Opaque
stringData:
  clientId: "{{ AUTH_CLIENT }}"
  clientSecret: "{{ AUTH_CLIENT_SECRET.clientsecret_info.value }}"
