apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
  namespace: dex
data:
  config.yaml: |
    issuer: https://dex-dex.apps-crc.testing

    storage:
      type: memory

    web:
      http: "0.0.0.0:5556"

    grpc:
      addr: "0.0.0.0:5557"

    telemetry:
      http: "0.0.0.0:5558"

    oauth2:
      skipApprovalScreen: true

    staticClients:
      - id: grafana
        name: Grafana
        redirectURIs:
          - https://grafana.apps-crc.testing/login/generic_oauth
        secretEnv: GRAFANA_SECRET
      - id: minio
        name: MinIO
        redirectURIs:
          - https://minio-console-minio.apps-crc.testing/oauth_callback
          - https://minio-minio.apps-crc.testing/oauth_callback
        secretEnv: MINIO_IDENTITY_OPENID_CLIENT_SECRET

    connectors:
      - type: openshift
        id: openshift
        name: OpenShift
        config:
          issuer: https://kubernetes.default.svc
          clientID: system:serviceaccount:dex:dex
          clientSecret: $OPENSHIFT_CLIENT_SECRET
          redirectURI: https://dex-dex.apps-crc.testing/callback
          groups:
            - system:authenticated
