apiVersion: v1
kind: Secret
metadata:
  namespace: group-sync-operator
  name: github-group-sync
type: Opaque
stringData:
  appId: "{{ GITHUB_GROUP_SYNC_APP_ID }}"
  privateKey: |-
    {{ lookup('file', GITHUB_GROUP_SYNC_APP_PRIVATE_KEY) | indent( width=4, first=false) }}
