apiVersion: v1
kind: Secret
metadata:
  namespace: keycloak
  name: keycloak-initial-admin
type: Opaque
stringData:
  admin-password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters') }}"
