---
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-group
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ CLUSTER_ADMIN_GROUP }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
