apiVersion: v1
kind: Secret
metadata:
  namespace: dex
  name: dex-clients
type: Opaque
stringData:
  GRAFANA_SECRET: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
  MINIO_IDENTITY_OPENID_CLIENT_SECRET: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
