apiVersion: v1
kind: Secret
metadata:
  namespace: minio
  name: minio-admin-credentials
type: Opaque
stringData:
  MINIO_IDENTITY_OPENID_CLIENT_SECRET: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('dex-clients'), namespace='dex')[0].data['MINIO_IDENTITY_OPENID_CLIENT_SECRET'] | b64decode }}"
  MINIO_ROOT_PASSWORD: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
  MINIO_ROOT_USER: "minio-admin"
