---
GITHUB_ORG: OCP-on-NERC
CLUSTER_ADMIN_GROUP: nerc-ops
SITE_NAMESPACE: ai-telemetry-cbca60
AUTH_NAMESPACE: "{{ SITE_NAMESPACE }}"
OPENSHIFT_APPS_DOMAIN: apps.shift.nerc.mghpcc.org
AUTH_HOST_NAME: keycloak.apps.obs.nerc.mghpcc.org
AUTH_URL: https://keycloak.apps.obs.nerc.mghpcc.org
AUTH_REALM: NERC
AUTH_CLIENT: ai-telemetry
WORKBENCH_SIZE: 20Gi
SITE_SHORT_NAME: aitelemetry
SITE_NAME: ai-telemetry
SITE_DISPLAY_NAME: AI Telemetry
SITE_DESCRIPTION: "AI telemetry on OpenShift dashboards"
SITE_MAIN_VERTICLE_PACKAGE: org.mghpcc.aitelemetry.verticle
SITE_POM_ARTIFACT_ID: aitelemetry
SITE_PORT: 10210
SITE_SRC: "/opt/app-root/src/{{ SITE_NAME }}"
SITE_THEME: dark
COMPUTATE_SRC: "/opt/app-root/src/computate"
COMPUTATE_VERTX_SRC: "/opt/app-root/src/computate-vertx"
SOLR_NAMESPACE: "{{ SITE_NAMESPACE }}"
DATABASE_NAMESPACE: "{{ SITE_NAMESPACE }}"
ADMIN_NAMESPACE: "{{ SITE_NAMESPACE }}"
ENABLE_FIWARE: false
FULFILLMENT_API_HOST_NAME: fulfillment-api-innabox.apps.hypershift1.nerc.mghpcc.org
FULFILLMENT_API_SSL: true
FULFILLMENT_API_PORT: 443

ESI_API_OPENSHIFT_SECRET: esi-uitest-cloud-config
ESI_API_SSL: "false"
ESI_API_HOST_NAME: "localhost"
ESI_API_PORT: "8081"

ENABLE_KAFKA: true
KAFKA_NAMESPACE: "{{ SITE_NAMESPACE }}"
KAFKA_SSL_KEYSTORE_SECRET: "kafka-{{ SITE_NAME }}"
KAFKA_SSL_TRUSTSTORE_SECRET: kafka-cluster-ca-cert
KAFKA_BROKERS: kafka-bootstrap:9093
KAFKA_GROUP: "esi-ai-telemetry"
KAFKA_SECURITY_PROTOCOL: SSL
KAFKA_SSL_KEYSTORE_TYPE: PKCS12
KAFKA_SSL_KEYSTORE_LOCATION: /opt/kafka/keystore/user.p12
KAFKA_SSL_KEYSTORE_SECRET: kafka-ai-telemetry
KAFKA_SSL_KEYSTORE_PASSWORD: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=KAFKA_SSL_KEYSTORE_SECRET, namespace=SITE_NAMESPACE)[0].data['user.password'] | b64decode }}"
KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
KAFKA_SSL_TRUSTSTORE_LOCATION: /opt/kafka/keystore/user.crt
KAFKA_SSL_TRUSTSTORE_SECRET: kafka-cluster-ca-cert
KAFKA_SSL_TRUSTSTORE_PASSWORD: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=KAFKA_SSL_KEYSTORE_SECRET, namespace=SITE_NAMESPACE)[0].data['ca.password'] | b64decode }}"

WORKBENCH_NAMES:
#  - USER_NAME: dheeraj
#  - USER_NAME: rh-csaggin
#  - USER_NAME: tzumainn
#  - USER_NAME: computate
#    WORKBENCH_ADMIN: true
#  - USER_NAME: isaiahstapleton
#  - USER_NAME: danniesh
#  - USER_NAME: schwesig
  - USER_NAME: tsisodia10
  - USER_NAME: ajamias
