apiVersion: v1
kind: Secret
metadata:
  namespace: keycloak
  name: postgres-pguser-keycloak
type: Opaque
stringData:
  password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters') }}"
